chore: log of execute function should go to stderr

diff --git a/bin/tag-publish-docker-image b/bin/tag-publish-docker-image
--- a/bin/tag-publish-docker-image
+++ b/bin/tag-publish-docker-image
@@ -78,7 +78,7 @@ isNotInTestMode () { ! [[ $TEST_MODE == true ]]; }
 
 execute () {
   if isNotInTestMode; then
-    eval $*
+    eval $* 1>&2
   fi
 }
 
@@ -130,5 +130,5 @@ else
   log "  No image to tag."
 fi
 
-# use the return value in stdout 
+# use the return value in stdout
 echo $RETURNVALUE
